source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HYBLib_Example', :exclusive => true do
  pod 'HYBLib', :path => '../'
end

target 'HYBLib_Tests', :exclusive => true do
  pod 'HYBLib', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
